key_metrics_changes = git.modified_files.grep(%r{\Arules/autogenerated-key-metrics-.*\.yml\z})

def markdown_list(items)
  items.map { |item| "1. `#{item}`" }.join("\n")
end

if key_metrics_changes.any?
  warn <<~MESSAGE
    This MR changes some autogenerated key metrics:

    #{markdown_list(key_metrics_changes)}

    Most of the time, this is OK, but please check the [autogenerated key metrics documentation](/rules/README.md#autogenerated-key-metrics) and make sure that this won't cause any issues with our overall SLA reporting.
  MESSAGE
end
