[
  import 'api.jsonnet',
  import 'ci-runners.jsonnet',
  import 'frontend.jsonnet',
  import 'git.jsonnet',
  import 'gitaly.jsonnet',
  import 'monitoring.jsonnet',
  import 'nfs.jsonnet',
  import 'patroni.jsonnet',
  import 'pgbouncer.jsonnet',
  import 'praefect.jsonnet',
  import 'registry.jsonnet',
  import 'sidekiq.jsonnet',
  import 'web.jsonnet',
]
