#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

rm -f "${SCRIPT_DIR}"/../rules/autogenerated-key-metrics*.yml

output_files="$(jsonnet --string --multi "${SCRIPT_DIR}/../rules" "${SCRIPT_DIR}/../metrics-catalog/recording-rules.jsonnet")"

if [[ -z "${output_files}" ]]; then
  echo "No output files"
  exit 1
fi

warning='# WARNING. DO NOT EDIT THIS FILE BY HAND. USE ./scripts/generate-key-metric-recording-rules.sh TO GENERATE IT
# YOUR CHANGES WILL BE OVERRIDDEN'

for i in ${output_files}; do
  mv "${i}" "${i}.tmp"

  (
    echo "$warning"
    "${SCRIPT_DIR}"/fix-prom-rules.rb "${i}.tmp"
  ) >"${i}"

  rm "${i}.tmp"
  echo "${i}"
done
