#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

(
  echo "# WARNING. DO NOT EDIT THIS FILE BY HAND. USE ./scripts/generate-sidekiq-worker-apdex-scores.sh TO GENERATE IT"
  echo "# YOUR CHANGES WILL BE OVERRIDDEN"
  jsonnet -S "${SCRIPT_DIR}/sidekiq-worker-apdex-scores.jsonnet"
) >  "${SCRIPT_DIR}/../rules/sidekiq-worker-apdex-scores.yml"
