#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

cd "$(dirname "${BASH_SOURCE[0]}")"

# Convert the service catalog yaml into a JSON file in a format thats consumable by jsonnet
ruby -rjson -ryaml -e "puts YAML.load(ARGF.read).to_json" ../services/service-catalog.yml >../services/service_catalog.json

function jsonnet_compile() {
  jsonnet -J . -J ../metrics-catalog/ -J ../services/ "$@"
}

(
  echo "# WARNING. DO NOT EDIT THIS FILE BY HAND. USE ./scripts/generate-sla-recording-rules.sh TO GENERATE IT"
  echo "# YOUR CHANGES WILL BE OVERRIDDEN"
  jsonnet_compile sla-recording-rules.jsonnet | "./fix-prom-rules.rb"
) >"../rules/autogenerated-sla-rules.yml"
