#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

mkdir -p "${SCRIPT_DIR}/../.gitlab/dashboards"
rm -f "${SCRIPT_DIR}"/../.gitlab/dashboards/*.yml

ruby -rjson -ryaml -e "puts YAML.load(ARGF.read).to_json" "${SCRIPT_DIR}/../services/service-catalog.yml" >"${SCRIPT_DIR}/../services/service_catalog.json"

output_dashboard_files="$(jsonnet -J "${SCRIPT_DIR}/../services" --string --multi "${SCRIPT_DIR}/../.gitlab/dashboards" "${SCRIPT_DIR}/../metrics-catalog/gitlab-dashboards.jsonnet")"
output_triage_files="$(jsonnet -J "${SCRIPT_DIR}/../services" --string --multi "${SCRIPT_DIR}/../.gitlab/dashboards" "${SCRIPT_DIR}/../metrics-catalog/gitlab-triage-dashboards.jsonnet")"
output_sla_file="$(jsonnet -J "${SCRIPT_DIR}/../services" --string --multi "${SCRIPT_DIR}/../.gitlab/dashboards" "${SCRIPT_DIR}/../metrics-catalog/gitlab-slas-dashboard.jsonnet")"

if [[ -z "${output_dashboard_files}" ]] && [[ -z "${output_triage_files}" ]] && [[ -z "${output_sla_file}" ]]; then
  echo "No output files"
  exit 1
fi

warning='# WARNING. DO NOT EDIT THIS FILE BY HAND. USE ./scripts/generate-gitlab-dashboards.sh TO GENERATE IT
# YOUR CHANGES WILL BE OVERRIDDEN'

for i in ${output_dashboard_files}; do
  mv "${i}" "${i}.tmp"

  (
    echo "$warning"
    "${SCRIPT_DIR}"/fix-prom-rules.rb "${i}.tmp"
  ) >"${i}"

  rm "${i}.tmp"
  echo "${i}"
done

for i in ${output_triage_files}; do
  mv "${i}" "${i}.tmp"

  (
    echo "$warning"
    "${SCRIPT_DIR}"/fix-prom-rules.rb "${i}.tmp"
  ) >"${i}"

  rm "${i}.tmp"
  echo "${i}"
done

for i in ${output_sla_file}; do
  mv "${i}" "${i}.tmp"

  (
    echo "$warning"
    "${SCRIPT_DIR}"/fix-prom-rules.rb "${i}.tmp"
  ) >"${i}"

  rm "${i}.tmp"
  echo "${i}"
done
