#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

mkdir -p "${SCRIPT_DIR}/../.gitlab/dashboards"
rm -f "${SCRIPT_DIR}"/../.gitlab/dashboards/triage-dashboard-*.yml

output_files="$(jsonnet --string --multi "${SCRIPT_DIR}/../.gitlab/dashboards" "${SCRIPT_DIR}/../metrics-catalog/gitlab-triage-dashboards.jsonnet")"

if [[ -z "${output_files}" ]]; then
  echo "No output files"
  exit 1
fi

warning='# WARNING. DO NOT EDIT THIS FILE BY HAND. USE ./scripts/generate-gitlab-triage-dashboards.sh TO GENERATE IT
# YOUR CHANGES WILL BE OVERRIDDEN'

for i in ${output_files}; do
  mv "${i}" "${i}.tmp"

  (
    echo "$warning"
    "${SCRIPT_DIR}"/fix-prom-rules.rb "${i}.tmp"
  ) >"${i}"

  rm "${i}.tmp"
  echo "${i}"
done
